export const INITIALIZE_CART = 'INITIALIZE_CART';
export const ADDCART = 'ADDCART';
export const SUBTRACTCART = 'SUBTRACTCART';
export const FUNCTIONTO_KEN = 'FUNCTIONTO_KEN';
export const SET_USER = 'SET_USER';
export const FUNCTION_CART_ANIME = 'FUNCTION_CART_ANIME';